"""whatsapp contact last_inbound_at

Revision ID: 23298edd298c
Revises: fdccd87431c1
Create Date: 2026-07-04 11:37:48.631301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23298edd298c'
down_revision: Union[str, None] = 'fdccd87431c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_contacts', sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_contacts', 'last_inbound_at')
    # ### end Alembic commands ###
