"""initial schema

Revision ID: 689a4fc00807
Revises: 
Create Date: 2026-07-04 10:34:39.703612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689a4fc00807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_white_label', sa.Boolean(), nullable=False),
    sa.Column('branding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('salon_spa_gym', 'clinic_healthcare', 'fnb', 'retail_fashion_jewellery', name='businesscategory'), nullable=False),
    sa.Column('tier', sa.Enum('starter', 'growth', 'scale', 'agency', name='businesstier'), nullable=False),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('churned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_businesses_category_tier', 'businesses', ['category', 'tier'], unique=False)
    op.create_index('ix_businesses_churned_at', 'businesses', ['churned_at'], unique=False)
    op.create_table('attribution_correlations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('signal_completeness_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('campaign_ref', sa.UUID(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lag_window_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attribution_signals_business_occurred', 'attribution_signals', ['business_id', 'occurred_at'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('credit_type', sa.Enum('ai', 'whatsapp', name='credittype'), nullable=False),
    sa.Column('delta', sa.Numeric(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('balance_after', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_ledger_business_created', 'credit_ledger', ['business_id', 'created_at'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('gbp', 'meta', 'whatsapp', name='platformname'), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('access_token_ref', sa.String(), nullable=True),
    sa.Column('sync_status', sa.Enum('healthy', 'degraded', 'broken', name='syncstatus'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('gbp', 'meta', 'whatsapp', name='platformname'), nullable=False),
    sa.Column('external_review_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ai_drafted_response', sa.Text(), nullable=True),
    sa.Column('response_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('platform_connections')
    op.drop_index('ix_credit_ledger_business_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('ix_attribution_signals_business_occurred', table_name='attribution_signals')
    op.drop_table('attribution_signals')
    op.drop_table('attribution_correlations')
    op.drop_index('ix_businesses_churned_at', table_name='businesses')
    op.drop_index('ix_businesses_category_tier', table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('agencies')
    # ### end Alembic commands ###

    # Alembic's autogenerate drops tables but not the standalone Postgres
    # ENUM types sa.Enum() created for them — drop explicitly or a re-run of
    # upgrade() after downgrade() fails with "type already exists".
    sa.Enum(name='businesscategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='businesstier').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='credittype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='platformname').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='syncstatus').drop(op.get_bind(), checkfirst=True)
