"""add missing FK indexes for scale

Revision ID: a0b5ddd92ecb
Revises: ba8db7915372
Create Date: 2026-07-04 21:46:29.385136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b5ddd92ecb'
down_revision: Union[str, None] = 'ba8db7915372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_businesses_agency_id', 'businesses', ['agency_id'], unique=False)
    op.create_index('ix_campaigns_business_id', 'campaigns', ['business_id'], unique=False)
    op.create_index('ix_oauth_states_business_id', 'oauth_states', ['business_id'], unique=False)
    op.create_index('ix_reviews_business_id', 'reviews', ['business_id'], unique=False)
    op.create_index('ix_subscriptions_business_id', 'subscriptions', ['business_id'], unique=False)
    op.create_index('ix_users_agency_id', 'users', ['agency_id'], unique=False)
    op.create_index('ix_users_business_id', 'users', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_business_id', table_name='users')
    op.drop_index('ix_users_agency_id', table_name='users')
    op.drop_index('ix_subscriptions_business_id', table_name='subscriptions')
    op.drop_index('ix_reviews_business_id', table_name='reviews')
    op.drop_index('ix_oauth_states_business_id', table_name='oauth_states')
    op.drop_index('ix_campaigns_business_id', table_name='campaigns')
    op.drop_index('ix_businesses_agency_id', table_name='businesses')
    # ### end Alembic commands ###
