"""oauth scaffold: refresh tokens, oauth_states

Revision ID: ba8db7915372
Revises: 23298edd298c
Create Date: 2026-07-04 17:17:42.267091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba8db7915372'
down_revision: Union[str, None] = '23298edd298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False: the 'platformname' Postgres enum already exists
    # (platform_connections.platform, reviews.platform) -- autogenerate
    # doesn't know that when a new table reuses the same Python Enum, and
    # emits a bare CREATE TYPE that fails with DuplicateObject otherwise.
    platformname_enum = postgresql.ENUM(
        "gbp", "meta", "whatsapp", name="platformname", create_type=False
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('platform', platformname_enum, nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.add_column('platform_connections', sa.Column('refresh_token_ref', sa.String(), nullable=True))
    op.add_column('platform_connections', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('platform_connections', sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_platform_connections_business_platform', 'platform_connections', ['business_id', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_platform_connections_business_platform', 'platform_connections', type_='unique')
    op.drop_column('platform_connections', 'scopes')
    op.drop_column('platform_connections', 'token_expires_at')
    op.drop_column('platform_connections', 'refresh_token_ref')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
