"""credit_ledger monotonic seq column

Revision ID: fdccd87431c1
Revises: 33c5d9bd7c24
Create Date: 2026-07-04 11:30:35.944303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdccd87431c1'
down_revision: Union[str, None] = '33c5d9bd7c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_ledger', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    # Named explicitly -- autogenerate left this unnamed (None), which
    # would make downgrade()'s drop_constraint(None, ...) fail outright.
    op.create_unique_constraint('uq_credit_ledger_seq', 'credit_ledger', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credit_ledger_seq', 'credit_ledger', type_='unique')
    op.drop_column('credit_ledger', 'seq')
    # ### end Alembic commands ###
